server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: 'library-project'
  liquibase:
    enabled: true
  datasource:
    username: 'postgres'
    password: 'password'
    url: 'jdbc:postgresql://localhost:5432/library'
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        format_sql: true
#        hbm2ddl:
#          auto: update
    open-in-view: true